site_name: Teamstudio Edition 33

nav:
  - 'index.md'
  - 'Installation Guide':
    - 'install/before.md'
    - 'install/server.md'
    - 'Installing Client-Based Modules':
      - 'install/client.md'
      - 'install/ciao.md'
      - 'install/icons.md'
    - 'install/trouble.md'
    - 'install/initializing.md'
    - 'install/running.md'
    - 'install/removing.md'
  - 'User Guide':
    - 'legal.md'
    - 'Teamstudio Analyzer':
      - 'analyzer/index.md'
      - 'Using Analyzer':
        - 'analyzer/starting.md'
        - 'analyzer/incremental.md'
        - 'Auditing A Design':
          - 'analyzer/auditing.md'
          - 'analyzer/auditoutput.md'
        - 'analyzer/designtab.md'
        - 'analyzer/startinganalysis.md'
      - 'The Analysis Output Database':
        - 'analyzer/output.md'
        - 'analyzer/comments.md'
        - 'analyzer/deleted.md'
        - 'analyzer/viewing.md'
        - 'analyzer/views.md'
        - 'analyzer/customizing.md'
        - 'analyzer/references.md'
      - 'The Audit Function':
        - 'analyzer/audit.md'
        - 'analyzer/auditcomponents.md'
        - 'analyzer/auditusingoutput.md'
      - 'Analyzer''s Filters':
        - 'analyzer/filters.md'
        - 'analyzer/filtersreviewing.md'
        - 'analyzer/filtersdisabling.md'
        - 'analyzer/filtersclasses.md'
        - 'analyzer/filtersseverity.md'
        - 'analyzer/filtersediting.md'
        - 'analyzer/filtersexamples.md'
      - 'Filters for Advanced Users':
        - 'analyzer/filtersadvanced.md'
        - 'analyzer/filtersrtcontains.md'
        - 'analyzer/filtersgetparentvalue.md'
        - 'analyzer/filtersgetchildvalues.md'
        - 'analyzer/filtersincludechildren.md'
        - 'analyzer/filterssearchall.md'
        - 'analyzer/filtersincludeparent.md'
        - 'analyzer/filtersaliasduplicate.md'
      - 'Calling Analyzer from LotusScript':
        - 'analyzer/script.md'
        - 'analyzer/scriptanalyze.md'
        - 'analyzer/scriptanalyze2.md'
        - 'analyzer/scriptanalyzeandaudit.md'
        - 'analyzer/scriptstringload.md'
        - 'analyzer/scriptflags.md'
        - 'analyzer/scriptctxfilter.md'
        - 'analyzer/scripterrors.md'
        - 'analyzer/scriptsample.md'
    - 'Teamstudio CIAO!':
      - 'ciao/index.md'
      - 'Using CIAO!':
        - 'ciao/about.md'
        - 'ciao/using.md'
        - 'Working with Elements':
          - 'ciao/designer.md'
          - 'ciao/checkout.md'
          - 'ciao/checkoutsafe.md'
          - 'ciao/undocheckout.md'
          - 'ciao/grab.md'
          - 'ciao/checkin.md'
          - 'ciao/recover.md'
          - 'ciao/history.md'
        - 'Making Versions':
          - 'ciao/version.md'
          - 'ciao/versionoptions.md'
          - 'ciao/versionrestore.md'
        - 'Reports':
          - 'ciao/reportactivity.md'
          - 'ciao/reportchange.md'
        - 'ciao/promoting.md'
        - 'ciao/preferences.md'
      - 'Administering CIAO!':
        - 'ciao/admin.md'
        - 'ciao/adminalternate.md'
        - 'ciao/adminenable.md'
        - 'ciao/adminadd.md'
        - 'ciao/admindocuments.md'
        - 'Issue Tracking':
          - 'ciao/issue.md'
          - 'ciao/issuerequire.md'
        - 'ciao/templates.md'
        - 'ciao/comments.md'
        - 'ciao/featureaccess.md'
        - 'CIAO! Config Information':
          - 'ciao/configbasics.md'
          - 'ciao/configwatch.md'
          - 'ciao/configauthority.md'
          - 'ciao/configissues.md'
          - 'ciao/configversioning.md'
      - 'Log Database Reference':
        - 'ciao/log.md'
        - 'ciao/logentries.md'
        - 'ciao/logviews.md'
        - 'ciao/logfields.md'
        - 'ciao/logforms.md'
        - 'ciao/logmove.md'
        - 'ciao/logacl.md'
      - 'Calling CIAO! from LotusScript':
        - 'ciao/script.md'
        - 'ciao/scriptchangelist.md'
        - 'ciao/scriptcheckoutreport.md'
        - 'ciao/scriptcheckinnote.md'
        - 'ciao/scriptmakeversion.md'
        - 'ciao/scriptstringload.md'
        - 'ciao/scriptagents.md'
    - 'Teamstudio Configurator':
      - 'configurator/index.md'
      - 'Using Configurator':
        - 'configurator/starting.md'
        - 'configurator/where.md'
        - 'configurator/results.md'
        - 'configurator/selecting.md'
        - 'Selecting Match Options for Searches':
          - 'configurator/wholewords.md'
          - 'configurator/accent.md'
          - 'configurator/case.md'
          - 'configurator/wildcards.md'
          - 'configurator/regex.md'
        - 'configurator/action.md'
        - 'configurator/match.md'
      - 'configurator/output.md'
      - 'configurator/databases.md'
      - 'Calling Configurator from LotusScript':
        - 'configurator/script.md'
        - 'configurator/scriptcompile.md'
        - 'configurator/scriptfar.md'
        - 'configurator/scriptstringload.md'
        - 'configurator/scripterrors.md'
    - 'Teamstudio Delta':
      - 'delta/index.md'
      - 'delta/how.md'
      - 'delta/using.md'
      - 'Comparing Elements or Documents':
        - 'delta/comparing.md'
        - 'delta/symbols.md'
        - 'delta/options.md'
        - 'delta/element.md'
        - 'Viewing Differences':
          - 'delta/differences.md'
          - 'delta/colors.md'
          - 'delta/locating.md'
          - 'delta/hidingidentical.md'
          - 'delta/tabbedtables.md'
        - 'delta/data.md'
        - 'delta/matching.md'
        - 'delta/nomatch.md'
        - 'delta/preferences.md'
        - 'delta/smartfilter.md'
      - 'delta/merging.md'
      - 'Creating Difference Reports':
        - 'delta/reports.md'
        - 'delta/reportoptions.md'
        - 'delta/reportsymbols.md'
        - 'delta/reportcolors.md'
        - 'delta/reportfilter.md'
        - 'delta/reportdata.md'
        - 'delta/reportviewing.md'
      - 'Calling Delta from LotusScript':
        - 'delta/script.md'
        - 'delta/scriptreport.md'
        - 'delta/scriptstringload.md'
    - 'Teamstudio Profiler':
      - 'profiler/index.md'
      - 'Profiler Client':
        - 'profiler/client.md'
        - 'profiler/running.md'
        - 'profiler/results.md'
        - 'profiler/calltree.md'
      - 'Profiler Server':
        - 'profiler/server.md'
        - 'profiler/configuration.md'
        - 'profiler/log.md'
      - 'profiler/troubleshooting.md'
    - 'Teamstudio Undo':
      - 'undo/index.md'
      - 'undo/configuring.md'
      - 'Using Undo':
        - 'undo/viewing.md'
        - 'undo/undoing.md'
    - 'Teamstudio Validator':
      - 'validator/index.md'
      - 'validator/starting.md'
      - 'validator/running.md'
      - 'validator/views.md'
      - 'validator/viewerror.md'
      - 'Common Errors':
        - 'validator/form.md'
        - 'validator/nodatabase.md'
        - 'validator/nodocument.md'
        - 'validator/inconsistent.md'
        - 'validator/keyword.md'
        - 'validator/nodependency.md'
        - 'validator/agentdata.md'
        - 'validator/conflict.md'
        - 'validator/invalidurl.md'
      - 'Calling Validator from LotusScript':
        - 'validator/script.md'
        - 'validator/scriptgeneratereport.md'
        - 'validator/scriptstringload.md'
  - 'release.md'

theme:
  name: material

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: 日本語
      link: ./ja/
      lang: ja
      
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  - i18n:
      default_language: en
      default_language_only: true
      languages:
        ja: 日本語
      nav_translations:
        ja:
          Using Undo: Undo の使用