site_name: Teamstudio Edition 33

nav:
  - 'index.md'
  - 'Installation Guide':
    - 'install/before.md'
    - 'install/server.md'
    - 'Installing Client-Based Modules':
      - 'install/client.md'
      - 'install/ciao.md'
      - 'install/icons.md'
    - 'install/trouble.md'
    - 'install/initializing.md'
    - 'install/running.md'
    - 'install/removing.md'
  - 'User Guide':
    - 'legal.md'
    - 'Teamstudio Analyzer':
      - 'analyzer/index.md'
      - 'Using Analyzer':
        - 'analyzer/starting.md'
        - 'analyzer/incremental.md'
        - 'Auditing A Design':
          - 'analyzer/auditing.md'
          - 'analyzer/auditoutput.md'
        - 'analyzer/designtab.md'
        - 'analyzer/startinganalysis.md'
      - 'The Analysis Output Database':
        - 'analyzer/output.md'
        - 'analyzer/comments.md'
        - 'analyzer/deleted.md'
        - 'analyzer/viewing.md'
        - 'analyzer/views.md'
        - 'analyzer/customizing.md'
        - 'analyzer/references.md'
      - 'The Audit Function':
        - 'analyzer/audit.md'
        - 'analyzer/auditcomponents.md'
        - 'analyzer/auditusingoutput.md'
      - 'Analyzer''s Filters':
        - 'analyzer/filters.md'
        - 'analyzer/filtersreviewing.md'
        - 'analyzer/filtersdisabling.md'
        - 'analyzer/filtersclasses.md'
        - 'analyzer/filtersseverity.md'
        - 'analyzer/filtersediting.md'
        - 'analyzer/filtersexamples.md'
      - 'Filters for Advanced Users':
        - 'analyzer/filtersadvanced.md'
        - 'analyzer/filtersrtcontains.md'
        - 'analyzer/filtersgetparentvalue.md'
        - 'analyzer/filtersgetchildvalues.md'
        - 'analyzer/filtersincludechildren.md'
        - 'analyzer/filterssearchall.md'
        - 'analyzer/filtersincludeparent.md'
        - 'analyzer/filtersaliasduplicate.md'
      - 'Calling Analyzer from LotusScript':
        - 'analyzer/script.md'
        - 'analyzer/scriptanalyze.md'
        - 'analyzer/scriptanalyze2.md'
        - 'analyzer/scriptanalyzeandaudit.md'
        - 'analyzer/scriptstringload.md'
        - 'analyzer/scriptflags.md'
        - 'analyzer/scriptctxfilter.md'
        - 'analyzer/scripterrors.md'
        - 'analyzer/scriptsample.md'
    - 'Teamstudio Profiler':
      - 'profiler/index.md'
      - 'Profiler Client':
        - 'profiler/client.md'
        - 'profiler/running.md'
        - 'profiler/results.md'
        - 'profiler/calltree.md'
      - 'Profiler Server':
        - 'profiler/server.md'
        - 'profiler/configuration.md'
        - 'profiler/log.md'
      - 'profiler/troubleshooting.md'
    - 'Teamstudio Undo':
      - 'undo/index.md'
      - 'undo/configuring.md'
      - 'Using Undo':
        - 'undo/viewing.md'
        - 'undo/undoing.md'
  - 'release.md'

theme:
  name: material

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: 日本語
      link: ./ja/
      lang: ja
      
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        ja: 日本語